service: wbot

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  profile: lex

package:
  exclude:
    - '**'
  include:
    - '*.py'

functions:
  lexHandler:
    handler: lambda.lambda_handler
    memorySize: 128
    timeout: 15
